@baseUrl = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkOTBhNzg0NS01MTZmLTQ0OTktODhiZS02MDk5MGQ0N2FiOGYiLCJlbWFpbCI6InBlZHJvQHRlc3RlLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc4MjIzMjI5OSwiZXhwIjoxNzgyMzE4Njk5fQ.K_ikm2lkaFS12T5Kvclrl_FTdqYG7D06tVRvsliiWaI
@itemId = cole_o_id_do_item_criado_aqui

### 1. Teste de Cadastro (Register)
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "name": "Pedro Alves de Paula",
  "email": "pedro@teste.com",
  "password": "UmaSenhaParaTeste$%132"
}

### 2. Teste de Login (Recebendo o JWT)
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "pedro@teste.com",
  "password": "UmaSenhaParaTeste$%132"
}

### 3. Teste do ValidationPipe (Forçando um erro de propósito)
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "name": "Teste de Erro",
  "email": "email_invalido_sem_arroba"
}
