@baseUrl = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkOTBhNzg0NS01MTZmLTQ0OTktODhiZS02MDk5MGQ0N2FiOGYiLCJlbWFpbCI6InBlZHJvQHRlc3RlLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc4MjIzMjI5OSwiZXhwIjoxNzgyMzE4Njk5fQ.K_ikm2lkaFS12T5Kvclrl_FTdqYG7D06tVRvsliiWaI
@itemId = cole_o_id_do_item_criado_aqui

### 1. Teste de Cadastro (Register)
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "name": "Pedro Alves de Paula",
  "email": "pedro@teste.com",
  "password": "UmaSenhaParaTeste$%132"
}

### 2. Teste de Login (Recebendo o JWT)
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "pedro@teste.com",
  "password": "UmaSenhaParaTeste$%132"
}

### 3. Teste do ValidationPipe (Forçando um erro de propósito)
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "name": "Teste de Erro",
  "email": "email_invalido_sem_arroba"
}
### ==========================================
### VARIÁVEIS GLOBAIS
### Dica: O REST Client permite criar variáveis para não precisar copiar e colar IDs
### ==========================================
# @baseUrl = http://localhost:3000
# @token = cole_o_seu_token_jwt_aqui
# @adminToken = cole_o_token_do_admin_aqui

@catalogItemId = cole_um_id_do_catalogo_aqui
@addressId = cole_um_id_de_endereco_aqui
@appointmentId = cole_um_id_de_agendamento_aqui

### ==========================================
### 1. AUTENTICAÇÃO (Auth)
### ==========================================

### Registrar Cliente
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "name": "Cliente Teste",
  "email": "cliente@teste.com",
  "password": "senha-segura-123"
}

### Login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "cliente@teste.com",
  "password": "senha-segura-123"
}
